name: WorkFlow DogBreed

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.7,name=iPhone 11']
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Pods
      run: |
        pod install
    - name: Build and Test
      run: |
        xcodebuild clean test -project Dog Breed.xcodeproj -scheme Dog Breeds -destination "${destination}" 
      env: 
        destination: ${{ matrix.destination }}
