name: WorkFlow DogBreed

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.7,name=iPhone 11']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build and Test
      run: swift build -v


